parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    eXpansion\Framework\Config\Services\ConfigManager:
        class: 'eXpansion\Framework\Config\Services\ConfigManager'
