parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    eXpansion\Framework\Config\Services\ConfigManagerInterface:
        class: 'eXpansion\Framework\Config\Services\ConfigManager'
        arguments:
            $filesystem: '@oneup_flysystem.expansion_config_filesystem'


    eXpansion\Framework\Config\Services\ConfigUiManager:
        class: 'eXpansion\Framework\Config\Services\ConfigUiManager'
