services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    eXpansion\Framework\Config\Ui\Fields\:
        resource: '../../Ui/Fields/*'
        tags:
            - {name: 'expansion.config.ui', data_provider: 'exp.menu.items'}