services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    eXpansion\Bundle\Acme\Plugins\:
        resource: '../../Plugins/*'

    eXpansion\Bundle\Acme\Plugins\TotoPlugin:
        arguments:
            $players: '@expansion.framework.core.user_groups.players'
        tags:
            - {name: 'expansion.plugin', data_provider: 'exp.application'}

    eXpansion\Bundle\Acme\Plugins\Test:
        arguments:
             $playergroup: '@expansion.framework.core.user_groups.players'
        tags:
            - {name: 'expansion.plugin', data_provider: 'mp.legacy.map'}
            - {name: 'expansion.plugin', data_provider: 'exp.timer'}
            - {name: 'expansion.plugin', data_provider: 'exp.application'}

    eXpansion\Bundle\Acme\Plugins\SmTest:
        class:  eXpansion\Bundle\Acme\Plugins\SmTest
        tags:
            - {name: 'expansion.plugin', data_provider: 'sm.player'}
            - {name: 'expansion.plugin', data_provider: 'sm.player.shoot'}



    eXpansion\Bundle\Acme\Plugins\Gui\WindowFactory:
            arguments:
                $name:  "test window"
                $sizeX:  180
                $sizeY:  90

    eXpansion\Bundle\Acme\Plugins\Gui\MemoryWidgetFactory:
            class: 'eXpansion\Bundle\Acme\Plugins\Gui\MemoryWidgetFactory'
            arguments:
                $name:  "memory"
                $posX: 80
                $posY: -85
                $sizeX: null
                $sizeY: null
