services:
    eXpansion\Bundle\WidgetBestCheckpoints\Plugins\BestCheckpoints:
        class: eXpansion\Bundle\WidgetBestCheckpoints\Plugins\BestCheckpoints
        autowire: true
        arguments:
                $players: '@expansion.framework.core.user_groups.players'
                $allPlayers: '@expansion.framework.core.user_groups.all_players'
        tags:

          - {name: 'expansion.plugin', data_provider: 'expansion.local_records.race'}
          - {name: 'expansion.plugin', data_provider: 'exp.widget_best_checkpoints.compatibility.tm'}
          - {name: 'expansion.plugin', data_provider: 'mp.legacy.map'}


# @todo fix widget dataproviders for laps mode, this works only now with ta...

    expansion.bundle.widget_best_checkpoints.data_providers.compatibility.tm:
        class: eXpansion\Framework\Core\DataProviders\EmptyDataProvider
        tags:
            - {name: expansion.dataprovider, provider: "exp.widget_best_checkpoints.compatibility.tm", interface: eXpansion\Framework\Core\Plugins\StatusAwarePluginInterface}
            - {name: expansion.dataprovider.compatibility, title: 'TM'}

    eXpansion\Bundle\WidgetBestCheckpoints\Plugins\Gui\BestCheckpointsWidgetFactory:
            class: eXpansion\Bundle\WidgetBestCheckpoints\Plugins\Gui\BestCheckpointsWidgetFactory
            autowire: true
            arguments:
                $name:  "BestCheckpoints"
                $posX: -120
                $posY: 88
                $sizeX: null
                $sizeY: null

    eXpansion\Bundle\WidgetBestCheckpoints\Plugins\Gui\UpdaterWidgetFactory:
            class: eXpansion\Bundle\WidgetBestCheckpoints\Plugins\Gui\UpdaterWidgetFactory
            autowire: true
            arguments:
                $name:  "BestCheckpoints Updater"
                $posX: 0
                $posY: 0
                $sizeX: null
                $sizeY: null
