parameters:
    eXpansion.local_records.nb_records: 100

services:
    _defaults:
        autowire: true
        public: true

    eXpansion\Bundle\LocalRecords\Model\RecordQueryBuilder:
        class: eXpansion\Bundle\LocalRecords\Model\RecordQueryBuilder

    eXpansion\Bundle\LocalRecords\Plugins\MenuItems:
        class: eXpansion\Bundle\LocalRecords\Plugins\MenuItems
        tags:
            - {name: 'expansion.plugin', data_provider: 'exp.menu.items'}
