parameters:
    expansion.storage.gamedata.mode.codes:
        0 : script
        1 : round
        2 : timeattack
        3 : team
        4 : laps
        5 : cup
        6 : stunts

    expansion.storage.gamedata.titles:
        'TMStadium@nadeo': 'TM'
        'TMStadium':       'TM'
        'TMValley@nadeo':  'TM'
        'TMValley':        'TM'
        'TMCanyon@nadeo':  'TM'
        'TMCanyon':        'TM'
        'TMLagoon@nadeo':  'TM'
        'TMLagoon':        'TM'
        'obstacle@smokegun': 'SM'

    expansion.framework.core.storage.data.player.class: eXpansion\Framework\Core\Storage\Data\Player

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    eXpansion\Framework\Core\Storage\:
        resource: "../../Storage/*"
        exclude: "../../Storage/Data/"

    eXpansion\Framework\Core\Storage\PlayerStorage:
        tags:
            - {name: expansion.plugin, data_provider: exp.timer}

    eXpansion\Framework\Core\Storage\GameDataStorage:
        arguments:
            $gameModeCodes: "%expansion.storage.gamedata.mode.codes%"
            $titles: "%expansion.storage.gamedata.titles%"

    eXpansion\Framework\Core\Storage\Data\PlayerFactory:
        arguments:
            $class: "%expansion.framework.core.storage.data.player.class%"
