services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    eXpansion\Bundle\DeveloperTools\Plugins\DevTools:
        class: eXpansion\Bundle\DeveloperTools\Plugins\DevTools
        arguments:
            $players: '@expansion.framework.core.user_groups.players'
        tags:
            - {name: 'expansion.plugin', data_provider: 'exp.application'}

    eXpansion\Bundle\DeveloperTools\Plugins\Gui\MemoryWidgetFactory:
            class: 'eXpansion\Bundle\Acme\Plugins\Gui\MemoryWidgetFactory'
            arguments:
                $name:  "memory"
                $posX: 80
                $posY: -85
                $sizeX: null
                $sizeY: null
