services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    expansion.admin_chat.chat_command.restart:
        class: eXpansion\Bundle\AdminChat\ChatCommand\AdminCommand
        arguments:
            $command:     "restart"
            $permission:  "restart"
            $aliases:     ['res', 'restartmap']
            $functionName: "restartMap"
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.shuffle_maplist:
        class: eXpansion\Bundle\AdminChat\ChatCommand\AdminShuffleCommand
        arguments:
            $command:      "shuffle"
            $permission:   "maps"
            $aliases:      []
            $logger: "@monolog.logger.admin"
    expansion.admin_chat.chat_command.cancel:
        class: eXpansion\Bundle\AdminChat\ChatCommand\AdminVoteCommand
        arguments:
            $command:      "cancel"
            $permission:   "votes"
            $aliases:      []
            $functionName: "cancelVote"
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.next:
        class: eXpansion\Bundle\AdminChat\ChatCommand\AdminCommand
        arguments:
            $command:      "next"
            $permission:   "next"
            $aliases:      ['skip', 'nextmap']
            $functionName: "nextMap"
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.set_server_name:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        arguments:
            $command:              "name"
            $permission:           "set_server_name"
            $aliases:              []
            $functionName:         "setServerName"
            $parameterDescription: 'sets new server name, uses "" if spaces used.'
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.save_matchsettings:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        arguments:
            $command:              "save"
            $permission:           "matchsettings"
            $aliases:              []
            $functionName:         "saveMatchSettings"
            $parameterDescription: 'match setting to save, ends with .txt'
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.load_matchsettings:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        arguments:
            $command:              "load"
            $permission:           "matchsettings"
            $aliases:              []
            $functionName:         "loadMatchSettings"
            $parameterDescription: 'match setting to load, ends with .txt'
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.set_server_comment:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        arguments:
            $command:              "comment"
            $permission:           "set_server_comment"
            $aliases:              []
            $functionName:         "setServerComment"
            $parameterDescription: 'sets new server comment, use "" if spaces used.'
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.kick:
        class: eXpansion\Bundle\AdminChat\ChatCommand\ReasonUserCommand
        arguments:
            $command:                    "kick"
            $permission:                 "kick"
            $aliases:                    []
            $functionName:               "kick"
            $parameterLoginDescription:  'Login of player to kick.'
            $parameterReasonDescription: 'The reason for kicking.'
            $logger: "@monolog.logger.admin"
    #
    # Commands to ban/unban a player and clean ban list.
    #
    expansion.admin_chat.chat_command.ban:
        class: eXpansion\Bundle\AdminChat\ChatCommand\ReasonUserCommand
        arguments:
            $command:              "ban"
            $permission:           "ban"
            $aliases:              []
            $functionName:         "ban"
            $parameterLoginDescription: 'Login of player to ban.'
            $parameterReasonDescription: 'The reason for banning.'
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.unban:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        arguments:
            $command:              "unban"
            $permission:           "unban"
            $aliases:              []
            $functionName:         "unBan"
            $parameterDescription: "Login of the player to unban"
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.cleanban:
        class: eXpansion\Bundle\AdminChat\ChatCommand\AdminCommand
        arguments:
            $command:      "cleanbanlist"
            $permission:   "cleanbanlist"
            $aliases:      []
            $functionName: "cleanBanList"
            $logger: "@monolog.logger.admin"
  #
    # Command to black/unblack a player and manage the blacklist
    #
    expansion.admin_chat.chat_command.black:
        class: eXpansion\Bundle\AdminChat\ChatCommand\ReasonUserCommand
        arguments:
            $command:              "black"
            $permission:           "black"
            $aliases:              []
            $functionName:         "banAndBlackList"
            $parameterLoginDescription: 'Login of player to black.'
            $parameterReasonDescription: 'The reason for black listing.'
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.unblack:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        arguments:
            $command:      "unblack"
            $permission:   "unblack"
            $aliases:      []
            $functionName:         "unBlacklist"
            $parameterDescription: "Login of the player to unblack"
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.cleanblacklist:
        class: eXpansion\Bundle\AdminChat\ChatCommand\AdminCommand
        arguments:
            $command:      "cleanblacklist"
            $permission:   "cleanblacklist"
            $aliases:      []
            $functionName: "cleanBlackList"
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.saveblacklist:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        arguments:
            $command:      "saveblacklist"
            $permission:   "saveblacklist"
            $aliases:      []
            $functionName:         "saveBlackList"
            $parameterDescription: "Filename to save the list"
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.loadblacklist:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        arguments:
            $command:      "loadblacklist"
            $permission:   "loadblacklist"
            $aliases:      []
            $functionName:         "loadBlackList"
            $parameterDescription: "Filename to load the list"
            $logger: "@monolog.logger.admin"

    #
    # Command to ignore/unignore users and manage the list.
    #
    expansion.admin_chat.chat_command.ignore:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        arguments:
            $command:              "ignore"
            $permission:           "ignore"
            $aliases:              []
            $functionName:         "ignore"
            $parameterDescription: "Login of the player to ignore."
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.unignore:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        arguments:
            $command:              "unignore"
            $permission:           "unignore"
            $aliases:              []
            $functionName:         "unignore"
            $parameterDescription: "Login of the player to unignore."
            $logger: "@monolog.logger.admin"

    #
    # Command to add/remove guests and manage the list
    #
    expansion.admin_chat.chat_command.addguest:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        arguments:
            $command:              "addguest"
            $permission:           "addguest"
            $aliases:              []
            $functionName:         "addGuest"
            $parameterDescription: "Login of the player to add a player to your guest list."
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.removeguest:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        arguments:
            $command:              "removeguest"
            $permission:           "removeguest"
            $aliases:              []
            $functionName:         "removeGuest"
            $parameterDescription: "Login of the player to remove from the guestlist."
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.cleanguestlist:
        class: eXpansion\Bundle\AdminChat\ChatCommand\AdminCommand
        arguments:
            $command:              "cleanguestlist"
            $permission:           "cleanguestlist"
            $aliases:              []
            $functionName:         "cleanGuestList"
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.saveguestlist:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        arguments:
            $command:              "saveguestlist"
            $permission:           "saveguestlist"
            $aliases:              []
            $functionName:         "saveGuestList"
            $parameterDescription: "Filename to save the list"
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.loadguestlist:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        arguments:
            $command:              "loadguestlist"
            $permission:           "loadguestlist"
            $aliases:              []
            $functionName:         "loadGuestList"
            $parameterDescription: "Filename to load the list"
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.planets:
        class: eXpansion\Bundle\AdminChat\ChatCommand\AdminReturnCommand
        arguments:
            $command:              "planets"
            $permission:           "planets"
            $aliases:              []
            $functionName:         "getServerPlanets"
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.password:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        arguments:
            $command:              "password"
            $permission:           "password"
            $aliases:              []
            $functionName:         "setServerPasswordForPlayer"
            $parameterDescription: "New server join password"
            $logger: "@monolog.logger.admin"

    expansion.admin_chat.chat_command.specpass:
        class: eXpansion\Bundle\AdminChat\ChatCommand\OneParameterCommand
        arguments:
            $command:              "specpassword"
            $permission:           "specpassword"
            $aliases:              []
            $functionName:         "setServerPasswordForSpectator"
            $parameterDescription: "New server spectator join password"
            $logger: "@monolog.logger.admin"
