services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    eXpansion\Bundle\Notifications\Plugins\Notifications:
        class: eXpansion\Bundle\Notifications\Plugins\Notifications
        arguments:
            $allPlayers: "@expansion.framework.core.user_groups.all_players"
        tags:
            - {name: 'expansion.plugin', data_provider: 'exp.custom_ui.compatibility.tm'

    