parameters:
    expansion.framework.game_maniaplanet.data_providers.map.class: eXpansion\Framework\GameManiaplanet\DataProviders\ScriptMapDataProvider
    expansion.framework.game_maniaplanet.data_providers.map.interface: eXpansion\Framework\GameManiaplanet\DataProviders\Listener\ListenerInterfaceMpScriptMap

    expansion.framework.game_maniaplanet.data_providers.match.class: eXpansion\Framework\GameManiaplanet\DataProviders\ScriptMatchDataProvider
    expansion.framework.game_maniaplanet.data_providers.match.interface: eXpansion\Framework\GameManiaplanet\DataProviders\Listener\ListenerInterfaceMpScriptMatch

    expansion.framework.game_maniaplanet.data_providers.podium.class: eXpansion\Framework\GameManiaplanet\DataProviders\PodiumDataProvider
    expansion.framework.game_maniaplanet.data_providers.podium.interface: eXpansion\Framework\GameManiaplanet\DataProviders\Listener\ListenerInterfaceMpScriptPodium

    expansion.framework.core.data_providers.chat_data_provider.class: eXpansion\Framework\GameManiaplanet\DataProviders\ChatDataProvider
    expansion.framework.core.data_providers.chat_data_provider.interface: eXpansion\Framework\GameManiaplanet\DataProviders\Listener\ListenerInterfaceMpLegacyChat

    expansion.framework.core.data_providers.chat_command_data_provider.class: eXpansion\Framework\GameManiaplanet\DataProviders\ChatCommandDataProvider
    expansion.framework.core.data_providers.chat_command_data_provider.interface: eXpansion\Framework\GameManiaplanet\DataProviders\Listener\ChatCommandInterface

    expansion.framework.core.data_providers.player_data_provider.class: eXpansion\Framework\GameManiaplanet\DataProviders\PlayerDataProvider
    expansion.framework.core.data_providers.player_data_provider.interface: eXpansion\Framework\GameManiaplanet\DataProviders\Listener\ListenerInterfaceMpLegacyPlayer

    expansion.framework.core.data_providers.map_data_provider.class: eXpansion\Framework\GameManiaplanet\DataProviders\MapListDataProvider
    expansion.framework.core.data_providers.map_data_provider.interface: eXpansion\Framework\GameManiaplanet\DataProviders\Listener\ListenerInterfaceMpLegacyMaplist

    expansion.framework.core.data_providers.match_data_provider.class: eXpansion\Framework\GameManiaplanet\DataProviders\MapDataProvider
    expansion.framework.core.data_providers.match_data_provider.interface: eXpansion\Framework\GameManiaplanet\DataProviders\Listener\ListenerInterfaceMpLegacyMap

    expansion.framework.core.data_providers.manialink_page_answer_provider.class: eXpansion\Framework\GameManiaplanet\DataProviders\ManialinkPageAnswerDataProvider
    expansion.framework.core.data_providers.manialink_page_answer_provider.interface: eXpansion\Framework\GameManiaplanet\DataProviders\Listener\ListenerInterfaceMpLegacyManialink

    expansion.framework.core.data_providers.script_data_provider.class: eXpansion\Framework\GameManiaplanet\DataProviders\ScriptDataProvider
    expansion.framework.core.data_providers.script_data_provider.interface: eXpansion\Framework\GameManiaplanet\DataProviders\Listener\ListenerInterfaceMpLegacyScript

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    expansion.framework.game_maniaplanet.data_providers.map:
        class: "%expansion.framework.game_maniaplanet.data_providers.map.class%"
        tags:
            - {name: expansion.dataprovider, provider: "mp.script.map", interface: "%expansion.framework.game_maniaplanet.data_providers.map.interface%"}
            - {name: expansion.dataprovider.compatibility, title: ALL, gamemode: script}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.StartMap_Start, method: onStartMapStart}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.StartMap_End, method: onStartMapEnd}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.EndMap_Start, method: onEndMapStart}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.EndMap_End, method: onEndMapEnd}

    expansion.framework.game_maniaplanet.data_providers.match:
        class: "%expansion.framework.game_maniaplanet.data_providers.match.class%"
        tags:
            - {name: expansion.dataprovider, provider: "mp.script.match", interface: "%expansion.framework.game_maniaplanet.data_providers.match.interface%"}
            - {name: expansion.dataprovider.compatibility, title: ALL, gamemode: script}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.StartMatch_Start, method: onStartMatchStart}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.StartMatch_End, method: onStartMatchEnd}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.EndMatch_Start, method: onEndMatchStart}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.EndMatch_End, method: onEndMatchEnd}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.StartTurn_Start, method: onStartTurnStart}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.StartTurn_End, method: onStartTurnEnd}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.EndTurn_Start, method: onEndTurnStart}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.EndTurn_End, method: onEndTurnEnd}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.StartRound_Start, method: onStartRoundStart}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.StartRound_End, method: onStartRoundEnd}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.EndRound_Start, method: onEndRoundStart}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.EndRound_End, method: onEndRoundEnd}

    expansion.framework.game_maniaplanet.data_providers.podium:
        class: "%expansion.framework.game_maniaplanet.data_providers.podium.class%"
        tags:
            - {name: expansion.dataprovider, provider: "mp.script.podium", interface: "%expansion.framework.game_maniaplanet.data_providers.podium.interface%"}
            - {name: expansion.dataprovider.compatibility, title: ALL, gamemode: script}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.Podium_Start, method: onPodiumStart}
            - {name: expansion.dataprovider.listener, event_name: Maniaplanet.Podium_End, method: onPodiumEnd}

    expansion.framework.core.data_providers.chat_data_provider:
        class: "%expansion.framework.core.data_providers.chat_data_provider.class%"
        tags:
            - {name: 'expansion.dataprovider', provider: "mp.legacy.chat", interface: "%expansion.framework.core.data_providers.chat_data_provider.interface%"}
            - {name: 'expansion.dataprovider.compatibility', title: 'ALL'}
            - {name: 'expansion.dataprovider.listener', event_name: 'PlayerChat', method: 'onPlayerChat'}

    expansion.framework.core.data_providers.chat_command_data_provider:
        class: "%expansion.framework.core.data_providers.chat_command_data_provider.class%"
        tags:
            - {name: 'expansion.dataprovider', provider: "expansion.chat_command_data", interface: "%expansion.framework.core.data_providers.chat_command_data_provider.interface%"}
            - {name: 'expansion.dataprovider.compatibility', title: 'ALL'}
            - {name: 'expansion.dataprovider.listener', event_name: PlayerChat, method: onPlayerChat}

    expansion.framework.core.data_providers.player_data_provider:
        class: "%expansion.framework.core.data_providers.player_data_provider.class%"
        tags:
            - {name: 'expansion.dataprovider', provider: "mp.legacy.player", interface: "%expansion.framework.core.data_providers.player_data_provider.interface%"}
            - {name: 'expansion.dataprovider.compatibility', title: 'ALL'}
            - {name: 'expansion.dataprovider.listener', event_name: PlayerConnect, method: onPlayerConnect}
            - {name: 'expansion.dataprovider.listener', event_name: PlayerDisconnect, method: onPlayerDisconnect}
            - {name: 'expansion.dataprovider.listener', event_name: PlayerInfoChanged, method: onPlayerInfoChanged}
            - {name: 'expansion.dataprovider.listener', event_name: PlayerAlliesChanged, method: onPlayerAlliesChanged}

    expansion.framework.core.data_providers.map_data_provider:
        class: "%expansion.framework.core.data_providers.map_data_provider.class%"
        tags:
            - {name: 'expansion.dataprovider', provider: "mp.legacy.maplist", interface: "%expansion.framework.core.data_providers.map_data_provider.interface%"}
            - {name: 'expansion.dataprovider.compatibility', title: 'ALL'}
            - {name: 'expansion.dataprovider.listener', event_name: MapListModified, method: onMapListModified}

    expansion.framework.core.data_providers.match_data_provider:
        class: "%expansion.framework.core.data_providers.match_data_provider.class%"
        tags:
            - {name: 'expansion.dataprovider', provider: "mp.legacy.map", interface: "%expansion.framework.core.data_providers.match_data_provider.interface%"}
            - {name: 'expansion.dataprovider.compatibility', title: 'ALL'}
            - {name: 'expansion.dataprovider.listener', event_name: BeginMap, method: onBeginMap}
            - {name: 'expansion.dataprovider.listener', event_name: EndMap, method: onEndMap}

    expansion.framework.core.data_providers.manialink_page_answer_provider:
        class: "%expansion.framework.core.data_providers.manialink_page_answer_provider.class%"
        tags:
            - {name: 'expansion.dataprovider', provider: "mp.legacy.manialink", interface: "%expansion.framework.core.data_providers.manialink_page_answer_provider.interface%"}
            - {name: 'expansion.dataprovider.compatibility', title: 'ALL'}
            - {name: 'expansion.dataprovider.listener', event_name: PlayerManialinkPageAnswer, method: onPlayerManialinkPageAnswer}

    expansion.framework.core.data_providers.vote_provider:
        class: eXpansion\Framework\GameManiaplanet\DataProviders\VoteDataProvider
        tags:
            - {name: 'expansion.dataprovider', provider: "mp.legacy.vote", interface: eXpansion\Framework\GameManiaplanet\DataProviders\Listener\ListenerInterfaceMpLegacyVote}
            - {name: 'expansion.dataprovider.compatibility', title: 'ALL'}
            - {name: 'expansion.dataprovider.listener', event_name: VoteUpdated, method: VoteUpdated}

    expansion.framework.core.data_providers.echo_provider:
        class: eXpansion\Framework\GameManiaplanet\DataProviders\EchoDataProvider
        tags:
            - {name: 'expansion.dataprovider', provider: "mp.legacy.echo", interface: eXpansion\Framework\GameManiaplanet\DataProviders\Listener\ListenerInterfaceMpLegacyEcho}
            - {name: 'expansion.dataprovider.compatibility', title: 'ALL'}
            - {name: 'expansion.dataprovider.listener', event_name: Echo, method: onEcho}

    expansion.framework.core.data_providers.bill_provider:
        class: eXpansion\Framework\GameManiaplanet\DataProviders\BillDataProvider
        tags:
            - {name: 'expansion.dataprovider', provider: "mp.legacy.bill", interface: eXpansion\Framework\GameManiaplanet\DataProviders\Listener\ListenerInterfaceMpLegacyBill}
            - {name: 'expansion.dataprovider.compatibility', title: 'ALL'}
            - {name: 'expansion.dataprovider.listener', event_name: BillUpdated, method: onBillUpdated}


    expansion.framework.core.data_providers.script_data_provider:
        class: "%expansion.framework.core.data_providers.script_data_provider.class%"
        tags:
            - {name: 'expansion.dataprovider', provider: "mp.legacy.script", interface: "%expansion.framework.core.data_providers.script_data_provider.interface%"}
            - {name: 'expansion.dataprovider.compatibility', title: ALL, gamemode: script}
            - {name: 'expansion.dataprovider.listener', event_name: ModeScriptCallbackArray, method: onModeScriptCallbackArray}

    # This provider doesen't provide anydata. just used to set api version.
    expansion.framework.core.data_providers.script_api_version_setter:
        class: eXpansion\Framework\GameManiaplanet\DataProviders\ScriptApiVersionSetterDataProvider
        tags:
            - {name: 'expansion.dataprovider', provider: "mp.script.api_set_version", interface: "%expansion.framework.core.data_providers.script_data_provider.interface%"}
            - {name: 'expansion.dataprovider.compatibility', title: ALL, gamemode: script}
