services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    expansion.bundle.votemanager.plugins.chat_commands:
        class: eXpansion\Framework\Core\Model\ChatCommand\ChatCommandPlugin
        arguments:
            -
              - '@eXpansion\Bundle\VoteManager\ChatCommand\Skip'
              - '@eXpansion\Bundle\VoteManager\ChatCommand\Restart'
              - '@eXpansion\Bundle\VoteManager\ChatCommand\Pass'
        tags:
            - {name: 'expansion.plugin', data_provider: 'expansion.chat_command_data'}

    eXpansion\Bundle\VoteManager\ChatCommand\Restart:
        class: eXpansion\Bundle\VoteManager\ChatCommand\VoteStart
        arguments:
            $command: 'replay'
            $aliases: ['res', 'restart']
            $voteTypeCode: 'Exp_RestartMap'

    eXpansion\Bundle\VoteManager\ChatCommand\Skip:
        class: eXpansion\Bundle\VoteManager\ChatCommand\VoteStart
        arguments:
            $command: 'skip'
            $aliases: ['nextmap']
            $voteTypeCode: 'Exp_NextMap'

    eXpansion\Bundle\VoteManager\ChatCommand\Pass:
        class: eXpansion\Bundle\VoteManager\ChatCommand\VotePass
        arguments:
            $command: 'pass'
            $permission: "votes"
            $aliases: []
