services:
    eXpansion\Bundle\CustomUi\Plugins\CustomUi:
        class: eXpansion\Bundle\CustomUi\Plugins\CustomUi
        autowire: true
        arguments:
          $players: "@expansion.framework.core.user_groups.all_players"
        tags:
          - {name: 'expansion.plugin', data_provider: 'exp.application'}
          - {name: 'expansion.plugin', data_provider: 'mp.legacy.player'}

    eXpansion\Bundle\CustomUi\Plugins\Gui\ChatHelperWidget:
        class: eXpansion\Bundle\CustomUi\Plugins\Gui\ChatHelperWidget
        autowire: true
        arguments:
          $name:  "Chat"
          $posX: -120
          $posY: -50
          $sizeX: null
          $sizeY: null

    eXpansion\Bundle\CustomUi\Plugins\Gui\CustomCheckpointWidget:
        class: eXpansion\Bundle\CustomUi\Plugins\Gui\CustomCheckpointWidget
        autowire: true
        arguments:
          $name:  "Checkpoints"
          $posX: 0
          $posY: 0
          $sizeX: null
          $sizeY: null

    eXpansion\Bundle\CustomUi\Plugins\Gui\CustomSpeedWidget:
        class: eXpansion\Bundle\CustomUi\Plugins\Gui\CustomSpeedWidget
        autowire: true
        arguments:
          $name:  "Speed"
          $posX: 140
          $posY: -70
          $sizeX: null
          $sizeY: null
