services:
    eXpansion\Bundle\CustomUi\Plugins\CustomUi:
        class: eXpansion\Bundle\CustomUi\Plugins\CustomUi
        autowire: true
        arguments:
          $allPlayers: "@expansion.framework.core.user_groups.all_players"
          $players: "@expansion.framework.core.user_groups.players"
        tags:
            - {name: 'expansion.plugin', data_provider: 'exp.application'}
# @todo make possible to have plugins without data providers.

    eXpansion\Bundle\CustomUi\Plugins\Gui\CustomScoreboardWidget:
        class: eXpansion\Bundle\CustomUi\Plugins\Gui\CustomScoreboardWidget
        autowire: true
        arguments:
          $name:  "Scoreboard"
          $posX: 0
          $posY: 0
          $sizeX: null
          $sizeY: null

    eXpansion\Bundle\CustomUi\Plugins\Gui\CustomCheckpointWidget:
        class: eXpansion\Bundle\CustomUi\Plugins\Gui\CustomCheckpointWidget
        autowire: true
        arguments:
          $name:  "Checkpoints"
          $posX: 0
          $posY: 0
          $sizeX: null
          $sizeY: null

    eXpansion\Bundle\CustomUi\Plugins\Gui\MarkersWidget:
        class: eXpansion\Bundle\CustomUi\Plugins\Gui\MarkersWidget
        autowire: true
        arguments:
          $name:  "Markers"
          $posX: 0
          $posY: 0
          $sizeX: null
          $sizeY: null


    eXpansion\Bundle\CustomUi\Plugins\Gui\CustomSpeedWidget:
        class: eXpansion\Bundle\CustomUi\Plugins\Gui\CustomSpeedWidget
        autowire: true
        arguments:
          $name:  "Speed"
          $posX: 140
          $posY: -70
          $sizeX: null
          $sizeY: null
