services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    expansion.framework.game_trackmania.data_providers.race:
        class: eXpansion\Framework\GameTrackmania\DataProviders\RaceDataProvider
        tags:
            - {name: expansion.dataprovider, provider: "tm.script.race", interface: eXpansion\Framework\GameTrackmania\DataProviders\Listener\RaceDataListenerInterface}
            - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script}
            - {name: expansion.dataprovider.listener, event_name: Trackmania.Event.WayPoint, method: onWayPoint }

    expansion.framework.game_trackmania.data_providers.player:
        class: eXpansion\Framework\GameTrackmania\DataProviders\PlayerEventsDataProvider
        tags:
            - {name: expansion.dataprovider, provider: "tm.script.player", interface: eXpansion\Framework\GameTrackmania\DataProviders\Listener\PlayerEventsListenerInterface}
            - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script}
            - {name: expansion.dataprovider.listener, event_name: Trackmania.Event.StartLine, method: onStartLine}
            - {name: expansion.dataprovider.listener, event_name: Trackmania.Event.GiveUp, method: onGiveUp}
            - {name: expansion.dataprovider.listener, event_name: Trackmania.Event.Respawn, method: onRespawn}

    expansion.framework.game_trackmania.data_providers.method_get_scores:
        class: eXpansion\Framework\GameTrackmania\DataProviders\MethodGetScoresDataProvider
        tags:
            - {name: expansion.dataprovider, provider: 'mp.method.get_scores', interface: eXpansion\Framework\Core\ScriptMethods\AbstractScriptMethod}
            - {name: expansion.dataprovider.compatibility, title: TM}
            - {name: expansion.dataprovider.listener, event_name: Trackmania.Scores, method: setScores}

    expansion.framework.game_trackmania.data_providers.script_base_rounds.method_get_number_laps:
        class: eXpansion\Framework\GameTrackmania\DataProviders\ScriptBaseRounds\MethodGetNumberLapsDataProvider
        tags:
          - {name: expansion.dataprovider, provider: 'mp.method.get_number_laps', interface: eXpansion\Framework\Core\ScriptMethods\AbstractScriptMethod}
          - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script, script: 'Rounds.Script.txt'}
          - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script, script: 'Cup.Script.txt'}
          - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script, script: 'Team.Script.txt'}
          - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script, script: 'Chase.Script.txt'}

    expansion.framework.game_trackmania.data_providers.script_time_attack.method_get_number_laps:
        class: eXpansion\Framework\GameTrackmania\DataProviders\ScriptBaseRounds\MethodGetNumberLapsDataProvider
        tags:
          - {name: expansion.dataprovider, provider: 'mp.method.get_number_laps', interface: eXpansion\Framework\Core\ScriptMethods\AbstractScriptMethod}
          - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script, script: 'TeamAttack.Script.txt'}
          - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script, script: 'TimeAttack.Script.txt'}
