services:
    _defaults:
        autowire: true
        public: true

    eXpansion\Bundle\LocalMapRatings\Plugin\Gui\MapRatingsWidget:
            class: eXpansion\Bundle\LocalMapRatings\Plugin\Gui\MapRatingsWidget
            arguments:
                $name:  "Map Ratings"
                $posX: 142
                $posY: 70
                $sizeX: null
                $sizeY: null
