services:
    _defaults:
        autowire: true
        public: true

    eXpansion\Bundle\LocalMapRatings\Services\:
        resource: '../../Services/*'

    eXpansion\Bundle\LocalMapRatings\DataProviders\MapRatingsDataProvider:
        class: eXpansion\Bundle\LocalMapRatings\DataProviders\MapRatingsDataProvider
        tags:
          - {name: 'expansion.dataprovider', provider: "exp.mapratings", interface: eXpansion\Bundle\LocalMapRatings\DataProviders\Listener\ListenerInterfaceExpMapRatings}
          - {name: 'expansion.dataprovider.compatibility', title: 'ALL'}
          - {name: 'expansion.dataprovider.listener', event_name: 'expansion.mapratings.loaded', method: 'onMapRatingsLoaded'}
          - {name: 'expansion.dataprovider.listener', event_name: 'expansion.mapratings.changed', method: 'onMapRatingsChanged'}
