services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    eXpansion\Bundle\Dedimania\Services\DedimaniaService:
        class: eXpansion\Bundle\Dedimania\Services\DedimaniaService

